# Generated by Django 4.1.3 on 2022-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.IntegerField()),
                ('years', models.IntegerField()),
                ('risk', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
